version: "3"

services:
    python-django:
        build: .
        container_name: "python-django"
        stdin_open: true
        tty: true
        volumes:
            - ./code:/code
        ports:
            - "8000:8000"
            - "80:80"
        networks:
            - backend
        # command: python3 manage.py runserver 0.0.0.0:8000

networks:
    backend:
        external: true
